version: '3.7'

services:
  postgres:
    image: postgres:14.1
    ports:
      - '8090:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: siragugal
      POSTGRES_PASSWORD: "8AlC-crBHbPxrS03OM3E7KiT2N8FIyBB"
    volumes:
      - siragugal_data:/var/lib/postgresql/data
  redis:
    image: redis:6.2.6
    ports:
      - '8091:6379'
    command: redis-server --requirepass "YuY_AOrclaMGNsZEnOIbgwaS2bm_Bb6-"
    environment:
      - REDIS_REPLICATION_MODE=master
volumes:
  siragugal_data:
